name: CI

on:
  push:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - 'docs/**'
      - 'Examples/**'
      - '**.md'
  pull_request:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - 'docs/**'
      - 'Examples/**'
      - '**.md'

jobs:
  build:
    name: win-build-and-test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dotnet info
      shell: pwsh
      run: dotnet --info

    - name: Install ThirdPartyLibraries
      shell: cmd
      run: dotnet tool install --global ThirdPartyLibraries.GlobalTool

    - name: Install psake
      shell: pwsh
      run: Install-Module -Name psake -Force

    - name: Build
      shell: pwsh
      run: .\Build\step-build.ps1

    - name: ThirdPartyNotices
      shell: pwsh
      run: .\Build\step-third-party-notices.ps1

    - name: Unit test net461
      shell: pwsh
      run: .\Build\step-unit-test.ps1 net461

    - name: Unit test netcoreapp2.1
      shell: pwsh
      run: .\Build\step-unit-test.ps1 netcoreapp2.1

    - name: Unit test netcoreapp3.1
      shell: pwsh
      run: .\Build\step-unit-test.ps1 netcoreapp3.1

    - name: Unit test net5.0
      shell: pwsh
      run: .\Build\step-unit-test.ps1 net5.0

    - name: Pack
      shell: pwsh
      run: .\Build\step-pack.ps1

    - name: Pack test
      shell: pwsh
      run: .\Build\step-pack-test.ps1

    - name: Artifact nuget packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: |
          .\build-out\*.nupkg
          .\build-out\*.snupkg

  sdk-test:
    name: linux-sdk-test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: nuget-packages
        path: build-out

    - name: List artifacts
      run: ls -R
      working-directory: build-out

    - name: Install psake
      shell: pwsh
      run: Install-Module -Name psake -Force

    - name: Dotnet info
      shell: pwsh
      run: dotnet --info

    - name: test Basic
      shell: pwsh
      run: .\Build\step-sdk-test-basic-github.ps1

    - name: test MessagePack
      shell: pwsh
      run: .\Build\step-sdk-test-messagepack-github.ps1

  benchmarks:
    name: linux-benchmarks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install psake
      shell: pwsh
      run: Install-Module -Name psake -Force

    - name: Dotnet info
      shell: pwsh
      run: dotnet --info

    - name: run benchmarks
      shell: pwsh
      run: .\Build\step-benchmarks-github.ps1

    - name: Artifact results
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks
        path: |
          Benchmarks/ServiceModel.Grpc.Benchmarks/bin/Release/net5.0/BenchmarkDotNet.Artifacts/results

